version: 0.92.{build}

os: Visual Studio 2017
image: Visual Studio 2017

environment:
  AppVeyor: APPVEYOR

branches:
  only:
    - develop
  except:
    - gh-pages

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration : Release

build:
  parallel: true
  project: ClosedXML.sln
  verbosity: minimal

before_build:
  - ps: if (Test-Path 'C:\Tools\NuGet43') { $nugetDir = 'C:\Tools\NuGet43' } else { $nugetDir = 'C:\Tools\NuGet' }
  - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe', "$nugetDir\NuGet.exe")
  - cmd: nuget update -self
  - nuget restore

artifacts:
  - path: ClosedXML/bin/Release/netstandard2.0/ClosedXML.dll
  - path: ClosedXML/bin/Release/net35/ClosedXML.dll
  - path: ClosedXML/bin/Release/net40/ClosedXML.dll
  - path: ClosedXML/bin/Release/net461/ClosedXML.dll

test:
  assemblies:
    only: 
      - ClosedXML_Tests/bin/Release/netcoreapp2.0/ClosedXML_Tests.dll
      - ClosedXML_Tests/bin/Release/net461/ClosedXML_Tests.dll
