version: 0.8.{build}
branches:
  # whitelist
  only:
    - develop

  # blacklist
  except:
    - gh-pages
# Build worker image (VM template)
image: Visual Studio 2017
environment:
  AppVeyor: APPVEYOR

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

build:
  parallel: true               # enable MSBuild parallel builds
  project: ClosedXML.sln       # path to Visual Studio solution or project
  verbosity: minimal

configuration : Release

#Restore
before_build:
  - ps: if (Test-Path 'C:\Tools\NuGet43') { $nugetDir = 'C:\Tools\NuGet43' } else { $nugetDir = 'C:\Tools\NuGet' }
  - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe', "$nugetDir\NuGet.exe")
  - cmd: nuget update -self
  - cmd: nuget
#  - cmd: nuget sources add -name OpenXML-MyGet -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
  - nuget restore

artifacts:
  - path: ClosedXML/bin/Release/net452/ClosedXML.dll
  - path: ClosedXML/bin/Release/net461/ClosedXML.dll
