name: .NET build and test
env:
  CURRENT_VERSION: 0.95.${{ github.run_number }}
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Publish Unit Test Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: TestResult
        path: "TestResult/**/*"

  deployRelease:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      env: 
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: |
          ls ./ClosedXML/bin/Release
          dotnet nuget push .\ClosedXML\bin\Release\*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
    - name: GithubReleasesPush
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.CURRENT_VERSION }}
        prerelease: false
        title: "Release Build ${{ env.CURRENT_VERSION }}"
        files: |
          ./ClosedXML/bin/Release/*.nupkg
          ./ClosedXML/bin/Release/*.snupkg

  deployTest:
    if: github.ref == 'refs/heads/develop'
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      env: 
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TEST_TOKEN }}
      if:  env.NUGET_TOKEN_EXISTS != ''
      run: |
          ls ./ClosedXML/bin/Release
          dotnet nuget push .\ClosedXML\bin\Release\*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json